#!/usr/bin/bash

if [ -f ~/moonlander-firmware.bin ]; then
   rm ~/moonlander-firmware.bin
fi

curl -L https://oryx.zsa.io/pDWJR/latest/binary --output ~/moonlander-firmware.bin

wally-cli ~/moonlander-firmware.bin 

