#!/usr/bin/env bash

switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t $1
    else
        tmux switch-client -t $1
    fi
}

has_session() {
    tmux list-sessions | grep -q "^$1:"
}

hydrate() {
    if [ -x $2/.tmux-sessionizer ]; then
        tmux send-keys -t $1 "./.tmux-sessionizer && clear" c-M
    elif [ -x $HOME/.tmux-sessionizer ]; then
        tmux send-keys -t $1 "$HOME/.tmux-sessionizer && clear" c-M
    fi
}

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find -L ~/Projects ~/.config  ~/.local ~/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr ":;,." "____")
tmux_running=$(pgrep tmux)
venv_dir="$selected/venv"

venv=""
if [[ -d $venv_dir ]]; then
    venv="PY_VENV=$venv_dir"
fi

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected -e "$venv"
    hydrate $selected_name $selected
    exit 0
fi

if ! has_session $selected_name; then
    tmux new-session -ds $selected_name -c $selected -e "$venv"
    hydrate $selected_name $selected
fi

switch_to $selected_name
