- 1.1.10
- _NAME: MX Vertical Wireless Mouse
  _absent: [hi-res-scroll, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    onboard_profiles, report_rate, pointer_speed, speed-change, backlight, backlight-timed, fn-swap, disable-keyboard-keys, crown-smooth, divert-crown,
    divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4096
  _modelId: B020407BC08A
  _sensitive: {change-host: false, divert-keys: false, dpi: false, lowres-scroll-mode: false, reprogrammable-keys: false}
  _serial: B5FF777A
  _unitId: D41D03E9
  _wpid: 407B
  change-host: null
  divert-keys: {82: 0, 83: 1, 86: 1, 253: 1}
  dpi: 4000
  lowres-scroll-mode: false
  persistent-remappable-keys: null
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 253: 253}
