#!/run/current-system/sw/bin/bash

# omarchy:summary=Update user-installed git themes

mapfile -t themes < <(omarchy-theme-extras)

for theme in "${themes[@]}"; do
  echo "Updating: $(basename "$theme")"
  git -C "$theme" pull
done
